G:
  block_compression: 0.4
  bn_size: 4
  growth_rate: 12
  level_compression: 0.5
  level_config:
  - [6, 6, 6, 6]
  - [6, 6]
  - [6]
  max_num_feature: 312
  num_init_features: 24
  ps_woReLU: false
  res_factor: 1.0
  residual_denseblock: false
data:
  input_size: [16]
  scale: [2]
test:
  dataset:
    downscale: True
    mean: [0.4485, 0.4375, 0.4046]
    path: {source: '', target: './data/datasets/DIV2K/DIV2K_train_HR/resized/'}
    stddev: [0.0003, 0.0003, 0.0003]
  fast_validation: -1
train:
  batch_size: 50
  dataset:
    downscale: True
    mean: [0.4485, 0.4375, 0.4046]
    path: {source: '', target: './data/datasets/DIV2K/DIV2K_train_HR/resized/'}
    stddev: [0.0003, 0.0003, 0.0003]
  epochs: 10000
  growing_steps: [0.12, 0.25, 0.45, 0.6, 1.0]
  io: {eval_epoch_freq: 50, save_img_freq: 250, save_model_freq: 1000, print_errors_freq: 1000}
  l1_loss_weight: 1.0
  lr: 0.0001
  lr_decay: 0.5
  lr_schedule_patience: 30
  smallest_lr: 1.0e-05
